spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merukari
    username: postgres
    password: postgres
  jmx:
    enabled: false
server:
  servlet:
    context-path: /merukari
